CREATE TABLE IF NOT EXISTS form_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    jumlah INT NOT NULL,
    pesan VARCHAR(1000) NOT NULL
);

ALTER TABLE form_data
ADD COLUMN pesan VARCHAR(1000) NOT NULL AFTER status;