# Generated by Django 4.1 on 2024-05-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('konfirmasi', models.CharField(choices=[('Hadir', 'Hadir'), ('Tidak Hadir', 'Tidak Hadir')], max_length=20, null=True)),
                ('jumlah', models.PositiveIntegerField(null=True)),
                ('pesan', models.CharField(max_length=1000, null=True)),
                ('waktu', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Undangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('no_wa', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('ket', models.CharField(choices=[('Sudah Dikirim', 'Sudah Dikirim'), ('Belum Dikirim', 'Belum Dikirim')], default='Belum Dikirim', max_length=20, null=True)),
            ],
        ),
    ]
